version: "3.8"
services:
  backend:
    build: ./backend
    container_name: chess-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: chess-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
